import type { PropsWithChildren } from 'react'
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "About Page Lol",
  description: "Generated by create next app",
};


export default function AboutLayout({ children }: PropsWithChildren<unknown>) {
    return children;
}
